name: Build migpt-server-new image

on:
  workflow_dispatch: 

env:
  IMAGE_NAME: migpt-server-new

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      id: build
      run: |
        set -e
        docker build . --file Dockerfile --tag image
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV

    - name: Upload firmware directory
      uses: actions/upload-artifact@main
      if: steps.build.outputs.status == 'success' && !cancelled()
      with:
        name: ${{ env.IMAGE_NAME }}
        path: ${{ env.FIRMWARE }}
